config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    root 'posts#index'
    devise_for :users
    resources :posts
    resources :categories
    resources :users
    resources :tags, only: [:show]
    resources :image_files, only: [:create, :destroy]
  end

  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get '/service-worker.js', to: 'pwa#service_worker'
  get '/manifest.json', to: 'pwa#manifest'
  get '/:category_id', to: 'static_pages#show_category'

  resources :posts do
    member do
      patch 'toggle_like'
    end
    collection do
      post :preview
      get :search
    end
  end
  resources :tags, only: [:show]

  match '*unmatched_route', to: 'application#raise_not_found', via: :all
end

app/models/user.rb
# frozen_string_literal: true

# Model for User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :lockable, :recoverable
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 6},
            presence: true, on: :create,
            confirmation: true
  validates :password_confirmation, presence: true, on: :create

  has_many :posts
  mount_uploader :avatar, AvatarUploader
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to admin_users_path, notice: t('.notice')
    else
      render :new
    end
  end

  def update
    if @user.update user_params
      redirect_to admin_users_path, notice: t('.notice')
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: t('.notice')
    else
      redirect_to admin_users_path, alert: t('.alert')
    end
  end

  protected

  def set_user
    @user = User.find params[:id]
  end

  def user_params
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    params.require(:user).permit :email, :name, :avatar, :description, :password, :password_confirmation
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
  def avatar_url(user)
    user.avatar.url || 'anonymous_user.png'
  end
end

app/views/admin/users/_user.html.erb
<tr class="user-<%= user.id %> user-row">
  <td class="text-center"><%= user_counter + 1 %></td>
  <td><%= image_tag avatar_url(user), class: 'rounded-circle list-avatar', style: 'width: 40px; height: 40px; object-fit: cover;' %></td>
  <td><span class="font-bold"><%= user.name %></span></td>
  <td class="text-muted"><%= user.email %></td>
  <td class="text-center">
    <%= link_to edit_admin_user_url(user), class: 'btn-secondary' do %>
        <i class="fa fa-pencil-square-o"></i>
      <% end %>
    <%= link_to admin_user_url(user), method: :delete, class: 'btn-danger', 'data-confirm': t('.data_confirm') do %>
      <i class="fa fa-trash-o"></i>
    <% end %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<%= form_for(@user, url: admin_user_path(@user), html: {method: :put, multipart: true}) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">Edit User</h4>
    </div>
    <div class="card-body">
      <div class="row">
        <!-- Avatar Section -->
        <div class="col-md-4 text-center mb-4">
          <label class="form-label font-bold mb-2">Profile Picture</label>
          <div class="rounded-circle mx-auto shadow-md" id="image-preview" 
               style="background-image: url(<%= asset_path avatar_url(@user) %>); 
                      width: 200px; height: 200px; background-size: cover; background-position: center; 
                      position: relative; overflow: hidden; border: 4px solid white;">
            <%= f.file_field :avatar, style: "opacity: 0; width: 100%; height: 100%; cursor: pointer;" %>
            <div style="position: absolute; bottom: 0; left: 0; right: 0; background: rgba(0,0,0,0.5); color: white; padding: 5px; font-size: 12px; pointer-events: none;">
              <i class="fa fa-camera"></i> Change
            </div>
          </div>
        </div>

        <!-- Form Fields -->
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group mb-4">
                <%= f.label :email, class: "form-label font-bold" %>
                <%= f.email_field :email, autofocus: true, class: "form-control" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group mb-4">
                <%= f.label :name, class: "form-label font-bold" %>
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group mb-4">
                <%= f.label :password, class: "form-label font-bold" %>
                <span class="text-sm text-muted"><i>(<%= t '.password_notice' %>)</i></span>
                <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group mb-4">
                <%= f.label :password_confirmation, class: "form-label font-bold" %>
                <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="form-group mb-4">
            <%= f.label :description, class: "form-label font-bold" %>
            <%= f.text_area :description, class: 'form-control', rows: 4 %>
          </div>

          <div class="form-actions text-right mt-4">
            <%= f.submit "Update User", class: "btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<div class="card">
  <div class="card-header">
    <h4 class="card-title">Users</h4>
    <div class="header-actions">
      <%= link_to new_admin_user_url, class: 'btn-primary' do %>
        <i class="fa fa-plus"></i> <%= t '.new' %>
      <% end %>
    </div>
  </div>
  <div class="card-body">
    <table class="modern-table">
      <thead>
        <tr>
          <th><%= t '.stt' %></th>
          <th class="no-sort"><%= t '.avatar' %></th>
          <th><%= t '.name' %></th>
          <th><%= t '.email' %></th>
          <th class="no-sort"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @users %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= form_for(@user, url: admin_users_path, html: {multipart: true}) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">New User</h4>
    </div>
    <div class="card-body">
      <div class="row">
        <!-- Avatar Section -->
        <div class="col-md-4 text-center mb-4">
          <label class="form-label font-bold mb-2">Profile Picture</label>
          <div class="rounded-circle mx-auto shadow-md" id="image-preview" 
               style="background-image: url(<%= asset_path avatar_url(@user) %>); 
                      width: 200px; height: 200px; background-size: cover; background-position: center; 
                      position: relative; overflow: hidden; border: 4px solid white;">
            <%= f.file_field :avatar, style: "opacity: 0; width: 100%; height: 100%; cursor: pointer;" %>
            <div style="position: absolute; bottom: 0; left: 0; right: 0; background: rgba(0,0,0,0.5); color: white; padding: 5px; font-size: 12px; pointer-events: none;">
              <i class="fa fa-camera"></i> Change
            </div>
          </div>
        </div>

        <!-- Form Fields -->
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group mb-4">
                <%= f.label :email, class: "form-label font-bold" %>
                <%= f.email_field :email, autofocus: true, class: "form-control" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group mb-4">
                <%= f.label :name, class: "form-label font-bold" %>
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group mb-4">
                <%= f.label :password, class: "form-label font-bold" %>
                <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group mb-4">
                <%= f.label :password_confirmation, class: "form-label font-bold" %>
                <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="form-group mb-4">
            <%= f.label :description, class: "form-label font-bold" %>
            <%= f.text_area :description, class: 'form-control', rows: 4 %>
          </div>

          <div class="form-actions text-right mt-4">
            <%= f.submit "Create User", class: "btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>