config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    root 'posts#index'
    devise_for :users
    resources :posts
    resources :categories
    resources :users
    resources :tags, only: [:show]
    resources :image_files, only: [:create, :destroy]
  end

  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get '/service-worker.js', to: 'pwa#service_worker'
  get '/manifest.json', to: 'pwa#manifest'
  get '/:category_id', to: 'static_pages#show_category'

  resources :posts do
    member do
      patch 'toggle_like'
    end
    collection do
      post :preview
      get :search
    end
  end
  resources :tags, only: [:show]

  match '*unmatched_route', to: 'application#raise_not_found', via: :all
end

app/views/admin/shared/_footer.html.erb
<footer class="admin-footer">
  <div>
    &copy; <span id="current-year"></span> <strong><%= t('title') %></strong>. Designed with <i class="fa fa-heart" style="color: #ef4444;"></i> for Creators.
  </div>
  <% content_for :javascript do %>
    <script type="text/javascript" charset="utf-8">
      $("#current-year").html(new Date().getFullYear())
    </script>
  <% end %>
</footer>

app/views/admin/shared/_head_nav.html.erb
<header class="admin-header">
  <div class="page-title">
    Dashboard / <span style="color: var(--primary-600);"><%= controller_name.humanize.titleize %></span>
  </div>

  <div class="header-actions">
    <div style="position: relative; margin-right: 1rem;">
      <i class="fa fa-search" style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: var(--neutral-400);"></i>
      <input type="text" placeholder="Search..." style="padding-left: 32px; width: 200px; background: rgba(255,255,255,0.5); border-color: transparent;">
    </div>

    <button type="button" class="btn-primary" data-toggle="modal" data-target="#upload-modal">
      <i class="fa fa-cloud-upload-alt"></i>
      <span>Upload</span>
    </button>
  </div>
</header>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admin/shared/_navigation.html.erb
<aside class="admin-sidebar">
  <div class="logo">
    <%= link_to admin_root_path do %>
      <i class="fa fa-layer-group"></i>
      <span><%= t('title') %></span>
    <% end %>
  </div>

  <nav class="nav-menu">
    <%= link_to admin_users_path, class: ('active' if request.path.start_with?(admin_users_path)) do %>
      <i class="fa fa-users"></i>
      <span><%= t('.user') %></span>
    <% end %>

    <%= link_to admin_categories_path, class: ('active' if request.path.start_with?(admin_categories_path)) do %>
      <i class="fa fa-tags"></i>
      <span><%= t('.category') %></span>
    <% end %>

    <%= link_to admin_posts_path, class: ('active' if request.path.start_with?(admin_posts_path)) do %>
      <i class="fa fa-file-text-o"></i>
      <span><%= t('.post') %></span>
    <% end %>
  </nav>

  <div class="user-profile">
    <%= link_to destroy_admin_user_session_path, method: :delete do %>
      <i class="fa fa-sign-out-alt"></i>
      <span><%= t('.logout') %></span>
    <% end %>
  </div>
</aside>

app/views/admin/shared/_upload_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="upload-modal" tabindex="-1" role="dialog" aria-labelledby="upload-modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Upload Images</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <i class="fa fa-times"></i>
        </button>
      </div>
      <div class="modal-body">
        <div id="upload-image">
          <%= form_tag admin_image_files_path, remote: true, multipart: true, id: 'upload-form' do %>
            <div class="upload-dropzone" id="upload-dropzone">
              <%= file_field_tag 'images[]', multiple: true, accept: 'image/*', id: 'upload-file-input' %>
              <div class="dropzone-content">
                <div class="dropzone-icon">
                  <i class="fa fa-cloud-upload"></i>
                </div>
                <p class="dropzone-text">Drag & drop images here</p>
                <p class="dropzone-subtext">or click to browse</p>
              </div>
              <div class="dropzone-selected" style="display: none;">
                <i class="fa fa-check-circle"></i>
                <span class="selected-count"></span>
              </div>
            </div>
            <div class="upload-actions">
              <%= button_tag type: :submit, class: 'btn-primary upload-submit-btn', id: 'upload-submit-btn', disabled: true do %>
                <i class="fa fa-cloud-upload"></i> Upload Files
              <% end %>
            </div>
          <% end %>
        </div>
        <div id="images-index">
          <%= render ImageFile.order(id: :desc).limit(5) %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).on('change', '#upload-file-input', function() {
    var files = this.files;
    var $dropzone = $('#upload-dropzone');
    var $btn = $('#upload-submit-btn');

    if (files.length > 0) {
      var text = files.length === 1 ? '1 file selected' : files.length + ' files selected';
      $dropzone.find('.dropzone-content').hide();
      $dropzone.find('.dropzone-selected').show().find('.selected-count').text(text);
      $dropzone.addClass('has-files');
      $btn.prop('disabled', false);
    } else {
      $dropzone.find('.dropzone-content').show();
      $dropzone.find('.dropzone-selected').hide();
      $dropzone.removeClass('has-files');
      $btn.prop('disabled', true);
    }
  });

  // Drag and drop support
  $(document).on('dragover dragenter', '#upload-dropzone', function(e) {
    e.preventDefault();
    e.stopPropagation();
    $(this).addClass('dragover');
  });

  $(document).on('dragleave drop', '#upload-dropzone', function(e) {
    e.preventDefault();
    e.stopPropagation();
    $(this).removeClass('dragover');
  });

  $(document).on('drop', '#upload-dropzone', function(e) {
    var files = e.originalEvent.dataTransfer.files;
    $('#upload-file-input')[0].files = files;
    $('#upload-file-input').trigger('change');
  });

  // Reset form when modal closes
  $(document).on('hidden.bs.modal', '#upload-modal', function() {
    $('#upload-form')[0].reset();
    $('#upload-dropzone').removeClass('has-files');
    $('#upload-dropzone .dropzone-content').show();
    $('#upload-dropzone .dropzone-selected').hide();
    $('#upload-submit-btn').prop('disabled', true);
  });
</script>